### PR TITLE
Bootstrap 3

### PR DESCRIPTION
**Pull request by cowai**
Hi,
First I would like to say that this is an awesome project! Just what I needed.

I had a fork of the current stable version which fixed the problem with accents. But I see that you have fixed this in this repo. I also have migrated to bootstrap 3. It's here if you want it. 
It is probably not the best markup, and its surely missing some classes for bootstrap 3. I used [this](http://getbootstrap.com/migration/) as a guide for the list changes that needed to be made.

### CODE REVIEW

**Comment by albertobeta** [comment]
Hi! Thank you for adding the support to bootstrap 3. This can definitely become the official default_modern theme :) Just a small remark in this regards: I noticed that the buttons Edit/Delete, More and Download have no style (i.e. background), while in the current theme they are black/greyish. Is this made on purpose or it's due to a different CSS class name? I think I would leave a colored background for the aforementioned buttons to make clear to the user they are actions in the interface. Thoughts?

**Comment by cowai** [comment]
Hello, I have added back the button styles. Can't explain why I forgot that :)
I also see now that the edit page is missing some styles. I have tried to fix some of the small things, but the whole form needs to be restructured with bootstrap 3 in mind. For example, all inputs needs to have form-control class, but that also makes it use width:100%. So still some work to be done there.

**Comment by cowai** [comment]
With bc58229, the edit page is now okay, in my opinion.

**Comment by albertobeta** [comment]
Thank you! The general idea for the admin area of PG is having a dashboard which is independent from the theme chosen for the public pages (wordpress and other CMS do the same), this would give a lot more flexibility in future. However, before doing that, I plan to release version 2.5 and it would be nice to have the new default_modern theme based on bootstrap3. The only issue I found in your code is the missing dropdown menu icon in smaller screen sizes. Now it's like this:
screen shot 2015-04-18 at 11 24 45

But it should have the 3 small horizontal bars like this
screen shot 2015-04-18 at 11 50 11

If you have a quick fix for that, thank you in advance :) Otherwise I'll look into the issue.

**Comment by cowai** [comment]
Good idea to separate the two. Much cleaner to do it that way.

I can look into it tonight or maybe tomorrow. It should be quite simple.

**Comment by cowai** [comment]
I got some time now. It was a simple fix.

**Comment by albertobeta** [comment]
thank you :)

**Pull request merged**
