### PR TITLE
Use Bcrypt encryption instead of md5 for login

### PR DESCRIPTION
**Pull request by venam**
I switched the deprecated md5 hashes to the default php bcrypt hash
function.

### CODE REVIEW

**Comment by tn5421** [comment]
Doesn't this bump up the required version of php to 5.5.0?

**Comment by venam** [comment]
Yes, you are right, it does.

Maybe instead of using the built in function we could use a polyfill.

**Comment by albertobeta** [comment]
That's precisely why I didn't merge it with the master branch. The strength of PG is that it has very minimal server requirements.

**Comment by tn5421** [comment]
He does have a point that something needs to be done.  md5 is incredibly insecure nowadays.

**Pull request closed without merging**
