### PR TITLE
Enhance pagination, show links for 5 pages, and next,

### PR DESCRIPTION
**Pull request by Fisiu**
prev, the first and the last.

Signed-off-by: Mariusz Fik fisiu@fidano.pl

### CODE REVIEW

**Comment by Fisiu** [comment]
My implementation, with some other fixes can be seen on: http://archiwum.radiooswiecim.pl/

**Comment by albertobeta** [comment]
Hi Mariusz, thanks for the contribution. Before merging it, some small things should be fixed.
First, there are two notices:
```Notice: Undefined variable: categoryURLforPagination in /Users/alberto/Sites/podcastgen/PodcastGenerator/core/functions.php on line 657```

```Notice: Undefined variable: CounterEpisodesInCategory in /Users/alberto/Sites/podcastgen/PodcastGenerator/core/functions.php on line 662```

Second, in your website it looks fantastic:
screen shot 2015-06-26 at 00 44 31

However, your pagination block doesn't have any associated style (pagination-wrapper) using the default themes shipped with PG, this is what appears with the standard default_modern theme. Could you please change the theme CSS so that it looks as cool as in your website?
 
screen shot 2015-06-26 at 00 43 51
 
Finally, it seems that your paginator should be placed in a block (pagination-wrapper) which is associated to clear:both in order to avoid to float around in some default themes, such as "exposure" or "syndicate":
screen shot 2015-06-26 at 00 42 58

Another question: is there any particular reason why you nested the function *pagin* inside the function *showPodcastEpisodes*? If not, I think it will be better to keep it outside *showPodcastEpisodes*, at the same level of all the other functions.

It would be great if you could fix the aforementioned issues before merging.
Thanks again!

**Comment by Fisiu** [comment]
Funcion is nested because I need access to variables You mention in first point. Of course, I can pass them as pagin() method params. Just let me know which solution You prefer.

CSS, ok, I'll try to improve a look in thems other then mine ;-)

**Comment by albertobeta** [comment]
I would pass them to the pagin() method and have the function not nested in another function possibly.
Thank you :)

**Pull request closed without merging**
